server:
  port: 8080
info:
  app:
    version: '@project.version@'
spring:
  application:
    name: '@project.artifactId@'
  rsocket:
    server:
      port: 8081
#  shell:
#    help:
#      enabled: true
#      long-names: help
#      short-names: h
#      command: help
  r2dbc:
    url: r2dbc:h2:mem:///${spring.r2dbc.name}?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#    url: r2dbc:mysql://${spring.r2dbc.username}:${spring.r2dbc.password}@127.0.0.1:3306/${spring.r2dbc.name}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: administrator
    name: testdb
  flyway:
    url: jdbc:h2:mem:${spring.r2dbc.name};DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS ${spring.r2dbc.name}
#    url: jdbc:mysql://${spring.r2dbc.username}:${spring.r2dbc.password}@127.0.0.1:3306/${spring.r2dbc.name}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    default-schema: ${spring.r2dbc.name}
    locations: classpath:db/migration/
    enabled: true
  liquibase:
    url: jdbc:h2:mem:${spring.r2dbc.name};DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS ${spring.r2dbc.name}
#    url: jdbc:mysql://${spring.r2dbc.username}:${spring.r2dbc.password}@127.0.0.1:3306/${spring.r2dbc.name}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    user: ${spring.r2dbc.password}
    password: ${spring.r2dbc.username}
    default-schema: ${spring.r2dbc.name}
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
#    change-log: db/changelog/changelog-master.xml

  output:
    ansi:
      enabled: always
springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    use-root-path: true
logging:
  level:
    org.springframework.data.r2dbc: TRACE
