server:
  port: 8080
info:
  app:
    version: '@project.version@'
spring:
  application:
    name: '@project.artifactId@'
  rsocket:
    server:
      port: 8081
#  shell:
#    help:
#      enabled: true
#      long-names: help
#      short-names: h
#      command: help
  flyway:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS testdb
    default-schema: testdb
    user: mysql
    password: mysql
    locations: classpath:db/changelog/flyway
    enabled: true
#  liquibase:
#    default-schema: testdb
#    enabled: true
#    password: mysql
#    user: mysql
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS testdb
#    change-log: db/changelog/db.changelog-master.yaml
##    change-log: db/changelog/changelog-master.xml
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: mysql
    password: mysql
    name: testdb
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.data.r2dbc: TRACE
